import { Course, Instructor } from "./utils/types";

export const instructors: Instructor[] = [
  // Original 4
  {
    id: "1",
    name: "Ava Patel",
    avatar: "/images/instructors/ava.jpg",
    expertise: "Web Development,React,JavaScript",
    bio: "Senior frontend engineer and passionate educator with 10+ years of experience.",
    coursesCount: 8,
  },
  {
    id: "2",
    name: "Liam Chen",
    avatar: "/images/instructors/liam.jpg",
    expertise: "TypeScript,Backend,Node.js",
    bio: "Backend specialist and open-source contributor, focused on scalable systems.",
    coursesCount: 5,
  },
  {
    id: "3",
    name: "Sophia Lee",
    avatar: "/images/instructors/sophia.jpg",
    expertise: "UI/UX,Design,Web Design",
    bio: "Award-winning designer and mentor, helping students build beautiful interfaces.",
    coursesCount: 6,
  },
  {
    id: "4",
    name: "Noah Smith",
    avatar: "/images/instructors/noah.jpg",
    expertise: "CSS,Responsive Design,Performance",
    bio: "CSS wizard and performance advocate, making the web faster and prettier.",
    coursesCount: 4,
  },
  // Added 46
  {
    id: "5",
    name: "Emma Garcia",
    avatar: "/images/instructors/emma.jpg",
    expertise: "Python,Data Science,Machine Learning",
    bio: "Data scientist with a passion for building intelligent applications and teaching others.",
    coursesCount: 7,
  },
  {
    id: "6",
    name: "Oliver Martinez",
    avatar: "/images/instructors/oliver.jpg",
    expertise: "AWS,DevOps,Cloud Computing",
    bio: "Certified AWS Solutions Architect helping developers master the cloud.",
    coursesCount: 9,
  },
  {
    id: "7",
    name: "Isabella Rodriguez",
    avatar: "/images/instructors/isabella.jpg",
    expertise: "Vue.js,Nuxt.js,Frontend",
    bio: "Core contributor to several Vue.js libraries and an advocate for progressive frameworks.",
    coursesCount: 5,
  },
  {
    id: "8",
    name: "James Wilson",
    avatar: "/images/instructors/james.jpg",
    expertise: "SQL,Databases,PostgreSQL",
    bio: "Database administrator with 15 years of experience in optimizing and managing large-scale databases.",
    coursesCount: 6,
  },
  {
    id: "9",
    name: "Charlotte Anderson",
    avatar: "/images/instructors/charlotte.jpg",
    expertise: "Mobile Development,React Native,iOS",
    bio: "Mobile engineer building cross-platform applications for startups and enterprises.",
    coursesCount: 4,
  },
  {
    id: "10",
    name: "Benjamin Taylor",
    avatar: "/images/instructors/benjamin.jpg",
    expertise: "Cybersecurity,Ethical Hacking,Networking",
    bio: "Cybersecurity expert focused on making the web a safer place for everyone.",
    coursesCount: 8,
  },
  {
    id: "11",
    name: "Mia Thomas",
    avatar: "/images/instructors/mia.jpg",
    expertise: "GraphQL,Apollo,APIs",
    bio: "API architect specializing in GraphQL for modern, flexible data layers.",
    coursesCount: 3,
  },
  {
    id: "12",
    name: "Lucas Moore",
    avatar: "/images/instructors/lucas.jpg",
    expertise: "Java,Spring Boot,Microservices",
    bio: "Enterprise Java developer with a deep understanding of microservice architecture.",
    coursesCount: 7,
  },
  {
    id: "13",
    name: "Amelia Jackson",
    avatar: "/images/instructors/amelia.jpg",
    expertise: "Figma,UI Design,Prototyping",
    bio: "Product designer who loves turning complex problems into simple, beautiful user interfaces.",
    coursesCount: 5,
  },
  {
    id: "14",
    name: "Henry White",
    avatar: "/images/instructors/henry.jpg",
    expertise: "Next.js,Vercel,Server-Side Rendering",
    bio: "Full-stack developer and evangelist for the Jamstack architecture.",
    coursesCount: 6,
  },
  {
    id: "15",
    name: "Evelyn Harris",
    avatar: "/images/instructors/evelyn.jpg",
    expertise: "Angular,RxJS,State Management",
    bio: "Lead frontend developer specializing in building complex single-page applications with Angular.",
    coursesCount: 4,
  },
  {
    id: "16",
    name: "Alexander Clark",
    avatar: "/images/instructors/alexander.jpg",
    expertise: "Docker,Kubernetes,CI/CD",
    bio: "DevOps engineer passionate about automating infrastructure and deployment pipelines.",
    coursesCount: 8,
  },
  {
    id: "17",
    name: "Abigail Lewis",
    avatar: "/images/instructors/abigail.jpg",
    expertise: "Go,Backend,Systems Programming",
    bio: "Go (Golang) enthusiast building high-performance backend services.",
    coursesCount: 3,
  },
  {
    id: "18",
    name: "Daniel Robinson",
    avatar: "/images/instructors/daniel.jpg",
    expertise: "Web Accessibility,WCAG,Semantic HTML",
    bio: "Accessibility advocate dedicated to creating inclusive web experiences for all users.",
    coursesCount: 5,
  },
  {
    id: "19",
    name: "Ella Walker",
    avatar: "/images/instructors/ella.jpg",
    expertise: "Web3,Solidity,Blockchain",
    bio: "Blockchain developer exploring the future of decentralized applications.",
    coursesCount: 4,
  },
  {
    id: "20",
    name: "Matthew Perez",
    avatar: "/images/instructors/matthew.jpg",
    expertise: "C#, .NET,Game Development",
    bio: "Software developer with a background in both enterprise .NET applications and indie game dev.",
    coursesCount: 6,
  },
  {
    id: "21",
    name: "Aria Hall",
    avatar: "/images/instructors/aria.jpg",
    expertise: "Svelte,SvelteKit,Frontend",
    bio: "Frontend developer who believes in building lean, fast, and joyful web applications with Svelte.",
    coursesCount: 3,
  },
  {
    id: "22",
    name: "David Young",
    avatar: "/images/instructors/david.jpg",
    expertise: "Rust,Performance,WebAssembly",
    bio: "Systems programmer exploring the power of Rust for web and command-line applications.",
    coursesCount: 2,
  },
  {
    id: "23",
    name: "Scarlett Allen",
    avatar: "/images/instructors/scarlett.jpg",
    expertise: "Project Management,Agile,Scrum",
    bio: "Certified Scrum Master helping teams deliver high-quality software efficiently.",
    coursesCount: 5,
  },
  {
    id: "24",
    name: "Joseph King",
    avatar: "/images/instructors/joseph.jpg",
    expertise: "Android,Kotlin,Mobile Development",
    bio: "Senior Android developer with experience shipping apps to millions of users on the Play Store.",
    coursesCount: 7,
  },
  {
    id: "25",
    name: "Grace Wright",
    avatar: "/images/instructors/grace.jpg",
    expertise: "Digital Marketing,SEO,Content Strategy",
    bio: "Digital marketer who helps developers and designers promote their work effectively.",
    coursesCount: 6,
  },
  {
    id: "26",
    name: "Samuel Scott",
    avatar: "/images/instructors/samuel.jpg",
    expertise: "Django,Python,Backend",
    bio: "Full-stack Python developer with a love for the Django web framework.",
    coursesCount: 5,
  },
  {
    id: "27",
    name: "Victoria Green",
    avatar: "/images/instructors/victoria.jpg",
    expertise: "iOS,Swift,SwiftUI",
    bio: "iOS engineer crafting beautiful and intuitive apps for the Apple ecosystem.",
    coursesCount: 6,
  },
  {
    id: "28",
    name: "Jackson Baker",
    avatar: "/images/instructors/jackson.jpg",
    expertise: "Testing,Jest,Cypress,Playwright",
    bio: "Quality Assurance engineer passionate about building robust and reliable automated tests.",
    coursesCount: 4,
  },
  {
    id: "29",
    name: "Chloe Adams",
    avatar: "/images/instructors/chloe.jpg",
    expertise: "Creative Coding,Three.js,WebGL",
    bio: "Creative technologist blending art and code to create interactive 3D web experiences.",
    coursesCount: 3,
  },
  {
    id: "30",
    name: "Christopher Nelson",
    avatar: "/images/instructors/christopher.jpg",
    expertise: "Firebase,Google Cloud,Serverless",
    bio: "Cloud engineer specializing in serverless architectures with Firebase and Google Cloud.",
    coursesCount: 7,
  },
  {
    id: "31",
    name: "Zoe Carter",
    avatar: "/images/instructors/zoe.jpg",
    expertise: "Motion Design,After Effects,UI Animation",
    bio: "Motion designer who brings interfaces to life with meaningful animations.",
    coursesCount: 4,
  },
  {
    id: "32",
    name: "Andrew Mitchell",
    avatar: "/images/instructors/andrew.jpg",
    expertise: "Ruby on Rails,Ruby,Backend",
    bio: "Veteran Rails developer and advocate for convention over configuration.",
    coursesCount: 6,
  },
  {
    id: "33",
    name: "Layla Perez",
    avatar: "/images/instructors/layla.jpg",
    expertise: "UX Research,User Personas,Interviewing",
    bio: "UX researcher focused on understanding user needs to inform product strategy.",
    coursesCount: 5,
  },
  {
    id: "34",
    name: "Joshua Roberts",
    avatar: "/images/instructors/joshua.jpg",
    expertise: "PHP,Laravel,Backend",
    bio: "PHP artisan and creator of popular open-source Laravel packages.",
    coursesCount: 8,
  },
  {
    id: "35",
    name: "Riley Turner",
    avatar: "/images/instructors/riley.jpg",
    expertise: "Data Visualization,D3.js,JavaScript",
    bio: "Data journalist and developer who tells stories with data on the web.",
    coursesCount: 4,
  },
  {
    id: "36",
    name: "Ryan Phillips",
    avatar: "/images/instructors/ryan.jpg",
    expertise: "Elixir,Phoenix,Functional Programming",
    bio: "Functional programming advocate building scalable, concurrent applications with Elixir.",
    coursesCount: 3,
  },
  {
    id: "37",
    name: "Nora Campbell",
    avatar: "/images/instructors/nora.jpg",
    expertise: "WordPress,PHP,Theme Development",
    bio: "WordPress expert developing custom themes and plugins for clients worldwide.",
    coursesCount: 9,
  },
  {
    id: "38",
    name: "Ethan Parker",
    avatar: "/images/instructors/ethan.jpg",
    expertise: "C++,Unreal Engine,Game Development",
    bio: "AAA game developer now sharing his knowledge on building games with C++ and Unreal Engine.",
    coursesCount: 5,
  },
  {
    id: "39",
    name: "Hannah Evans",
    avatar: "/images/instructors/hannah.jpg",
    expertise: "Technical Writing,Documentation,Git",
    bio: "Technical writer passionate about creating clear, concise, and helpful developer documentation.",
    coursesCount: 4,
  },
  {
    id: "40",
    name: "Caleb Edwards",
    avatar: "/images/instructors/caleb.jpg",
    expertise: "Linux,Bash Scripting,System Administration",
    bio: "SysAdmin and Linux power user who loves the command line.",
    coursesCount: 6,
  },
  {
    id: "41",
    name: "Lillian Collins",
    avatar: "/images/instructors/lillian.jpg",
    expertise: "Tailwind CSS,Utility-First,CSS",
    bio: "Frontend developer and huge fan of the utility-first approach with Tailwind CSS.",
    coursesCount: 3,
  },
  {
    id: "42",
    name: "Isaac Stewart",
    avatar: "/images/instructors/isaac.jpg",
    expertise: "Electron,Desktop Apps,JavaScript",
    bio: "Building cross-platform desktop applications with web technologies like Electron.",
    coursesCount: 2,
  },
  {
    id: "43",
    name: "Aubrey Sanchez",
    avatar: "/images/instructors/aubrey.jpg",
    expertise: "Blender,3D Modeling,Animation",
    bio: "3D artist bringing ideas to life with Blender for games, web, and animation.",
    coursesCount: 5,
  },
  {
    id: "44",
    name: "Christian Morris",
    avatar: "/images/instructors/christian.jpg",
    expertise: "Machine Learning Ops,MLOps,Kubeflow",
    bio: "MLOps engineer focused on streamlining the lifecycle of machine learning models.",
    coursesCount: 4,
  },
  {
    id: "45",
    name: "Addison Rogers",
    avatar: "/images/instructors/addison.jpg",
    expertise: "Flutter,Dart,Mobile Development",
    bio: "Building beautiful, natively compiled applications for mobile, web, and desktop from a single codebase.",
    coursesCount: 6,
  },
  {
    id: "46",
    name: "Hunter Reed",
    avatar: "/images/instructors/hunter.jpg",
    expertise: "API Design,REST,OpenAPI",
    bio: "Software architect specializing in designing robust and developer-friendly APIs.",
    coursesCount: 4,
  },
  {
    id: "47",
    name: "Stella Cook",
    avatar: "/images/instructors/stella.jpg",
    expertise: "Low-Code,No-Code,Bubble.io",
    bio: "Empowering non-technical founders to build and launch their own applications without code.",
    coursesCount: 5,
  },
  {
    id: "48",
    name: "Julian Morgan",
    avatar: "/images/instructors/julian.jpg",
    expertise: "Haskell,Functional Programming,Compilers",
    bio: "Computer scientist and functional programming purist with a love for type theory.",
    coursesCount: 2,
  },
  {
    id: "49",
    name: "Paisley Bell",
    avatar: "/images/instructors/paisley.jpg",
    expertise: "Content Management Systems,Strapi,Headless CMS",
    bio: "Developer advocate for headless CMS architecture, focusing on Strapi and Sanity.",
    coursesCount: 4,
  },
  {
    id: "50",
    name: "Leo Murphy",
    avatar: "/images/instructors/leo.jpg",
    expertise: "Web Performance,Core Web Vitals,Optimization",
    bio: "Performance engineer obsessed with shaving milliseconds off of load times.",
    coursesCount: 5,
  },
];


export const courses: Course[] = [
  // Original 5
  {
    id: "1",
    title: "Web Development Bootcamp",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Web Development,HTML,CSS,JavaScript",
    price: 99,
    updatedAt: "2025-06-28T12:00:00Z",
  },
  {
    id: "2",
    title: "Learn Web Design from Scratch",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Web Design,UI/UX,HTML,CSS",
    price: 89,
    updatedAt: "2025-06-25T09:30:00Z",
  },
  {
    id: "3",
    title: "JavaScript Essentials",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "JavaScript,Programming,Frontend",
    price: 59,
    updatedAt: "2025-06-20T10:00:00Z",
  },
  {
    id: "4",
    title: "Responsive Web Design",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Responsive,Web Design,Mobile,CSS",
    price: 79,
    updatedAt: "2025-06-18T14:30:00Z",
  },
  {
    id: "5",
    title: "Advanced CSS Techniques",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "CSS,Web Development,Advanced",
    price: 69,
    updatedAt: "2025-06-15T16:45:00Z",
  },
  // Added 45
  {
    id: "6",
    title: "The Complete React Developer Course (w/ Redux)",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "React,JavaScript,Frontend,Redux",
    price: 119,
    updatedAt: "2025-07-01T11:00:00Z",
  },
  {
    id: "7",
    title: "Node.js, Express, MongoDB & More: The Complete Bootcamp",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Node.js,Backend,MongoDB,Express",
    price: 129,
    updatedAt: "2025-07-02T15:00:00Z",
  },
  {
    id: "8",
    title: "Mastering TypeScript",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "TypeScript,JavaScript,Programming",
    price: 89,
    updatedAt: "2025-06-29T18:00:00Z",
  },
  {
    id: "9",
    title: "UI & UX Design using Figma",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "UI/UX,Figma,Design,Prototyping",
    price: 109,
    updatedAt: "2025-07-05T09:00:00Z",
  },
  {
    id: "10",
    title: "Python for Data Science and Machine Learning Bootcamp",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Python,Data Science,Machine Learning",
    price: 149,
    updatedAt: "2025-07-10T14:00:00Z",
  },
  {
    id: "11",
    title: "AWS Certified Solutions Architect - Associate 2025",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "AWS,Cloud,DevOps,Certification",
    price: 99,
    updatedAt: "2025-07-08T10:20:00Z",
  },
  {
    id: "12",
    title: "Docker and Kubernetes: The Complete Guide",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Docker,Kubernetes,DevOps,Containers",
    price: 139,
    updatedAt: "2025-07-12T16:30:00Z",
  },
  {
    id: "13",
    title: "The Ultimate Guide to SQL and PostgreSQL",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "SQL,PostgreSQL,Databases,Backend",
    price: 79,
    updatedAt: "2025-06-11T11:45:00Z",
  },
  {
    id: "14",
    title: "Vue - The Complete Guide (incl. Vue Router & Vuex)",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Vue.js,JavaScript,Frontend",
    price: 119,
    updatedAt: "2025-07-03T13:15:00Z",
  },
  {
    id: "15",
    title: "React Native - The Practical Guide [2025 Edition]",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "React Native,Mobile,iOS,Android",
    price: 129,
    updatedAt: "2025-07-11T08:00:00Z",
  },
  {
    id: "16",
    title: "Next.js & React - The Complete Guide",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Next.js,React,SSR,Frontend",
    price: 109,
    updatedAt: "2025-07-14T12:00:00Z",
  },
  {
    id: "17",
    title: "GraphQL with React: The Complete Developers Guide",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "GraphQL,React,API,Apollo",
    price: 99,
    updatedAt: "2025-06-27T10:00:00Z",
  },
  {
    id: "18",
    title: "Ethical Hacking: An Introduction",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Cybersecurity,Hacking,Security",
    price: 149,
    updatedAt: "2025-07-15T19:00:00Z",
  },
  {
    id: "19",
    title: "Java Programming Masterclass",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Java,Programming,Backend,Spring",
    price: 109,
    updatedAt: "2025-07-04T17:30:00Z",
  },
  {
    id: "20",
    title: "Web Accessibility: Learn Best Practices",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Accessibility,WCAG,HTML,Frontend",
    price: 69,
    updatedAt: "2025-06-22T14:00:00Z",
  },
  {
    id: "21",
    title: "Angular - The Complete Guide (2025 Edition)",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Angular,TypeScript,Frontend",
    price: 119,
    updatedAt: "2025-07-18T11:00:00Z",
  },
  {
    id: "22",
    title: "Svelte.js - The Complete Guide",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Svelte,SvelteKit,JavaScript,Frontend",
    price: 89,
    updatedAt: "2025-07-06T13:45:00Z",
  },
  {
    id: "23",
    title: "Go: The Complete Developer's Guide (Golang)",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Go,Golang,Backend,Programming",
    price: 99,
    updatedAt: "2025-06-30T20:00:00Z",
  },
  {
    id: "24",
    title: "Blockchain and Solidity: The Complete Developer's Guide",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Web3,Blockchain,Solidity,Ethereum",
    price: 159,
    updatedAt: "2025-07-20T10:00:00Z",
  },
  {
    id: "25",
    title: "C# Basics for Beginners: Learn C# Fundamentals",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "C#,.NET,Programming,Backend",
    price: 79,
    updatedAt: "2025-07-09T09:30:00Z",
  },
  {
    id: "26",
    title: "The Complete 2025 Web Performance Bootcamp",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Performance,Optimization,Core Web Vitals",
    price: 89,
    updatedAt: "2025-07-19T14:00:00Z",
  },
  {
    id: "27",
    title: "Automated Software Testing with Cypress",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Testing,Cypress,E2E,QA",
    price: 99,
    updatedAt: "2025-07-16T15:15:00Z",
  },
  {
    id: "28",
    title: "Agile Crash Course: Agile Project Management",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Agile,Scrum,Project Management",
    price: 49,
    updatedAt: "2025-06-13T10:00:00Z",
  },
  {
    id: "29",
    title: "Android App Development Masterclass using Kotlin",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Android,Kotlin,Mobile",
    price: 129,
    updatedAt: "2025-07-21T11:30:00Z",
  },
  {
    id: "30",
    title: "Digital Marketing Masterclass - 20 Courses in 1",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Marketing,SEO,Social Media",
    price: 179,
    updatedAt: "2025-07-22T16:00:00Z",
  },
  {
    id: "31",
    title: "Django 4 - The Complete Guide",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Django,Python,Backend",
    price: 119,
    updatedAt: "2025-07-17T18:00:00Z",
  },
  {
    id: "32",
    title: "iOS & Swift - The Complete iOS App Development Bootcamp",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "iOS,Swift,Mobile,SwiftUI",
    price: 129,
    updatedAt: "2025-07-23T09:00:00Z",
  },
  {
    id: "33",
    title: "Creative Coding with Three.js & WebGL",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Three.js,WebGL,3D,JavaScript",
    price: 109,
    updatedAt: "2025-07-13T20:00:00Z",
  },
  {
    id: "34",
    title: "The Complete Firebase & Google Cloud Bootcamp",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Firebase,Google Cloud,Serverless",
    price: 99,
    updatedAt: "2025-07-24T14:30:00Z",
  },
  {
    id: "35",
    title: "UI Motion Design with After Effects",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Motion Design,UI/UX,Animation",
    price: 89,
    updatedAt: "2025-06-26T19:00:00Z",
  },
  {
    id: "36",
    title: "Ruby on Rails 7: The Complete Guide",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Ruby,Rails,Backend",
    price: 119,
    updatedAt: "2025-07-25T10:00:00Z",
  },
  {
    id: "37",
    title: "UX Research at Scale",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "UX Research,User Experience,Design",
    price: 79,
    updatedAt: "2025-07-07T16:45:00Z",
  },
  {
    id: "38",
    title: "PHP with Laravel for Beginners - Become a Master",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "PHP,Laravel,Backend",
    price: 109,
    updatedAt: "2025-07-26T11:00:00Z",
  },
  {
    id: "39",
    title: "Data Visualization with D3.js",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "D3.js,Data Visualization,JavaScript",
    price: 99,
    updatedAt: "2025-07-27T13:00:00Z",
  },
  {
    id: "40",
    title: "Learn Elixir & Phoenix - From Beginner to Pro",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Elixir,Phoenix,Functional,Backend",
    price: 99,
    updatedAt: "2025-07-28T15:00:00Z",
  },
  {
    id: "41",
    title: "WordPress Theme Development with Bootstrap",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "WordPress,PHP,Themes",
    price: 89,
    updatedAt: "2025-07-29T17:00:00Z",
  },
  {
    id: "42",
    title: "Unreal Engine 5 C++ Developer: Learn C++ & Make Games",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "C++,Unreal Engine,Game Development",
    price: 199,
    updatedAt: "2025-07-30T19:00:00Z",
  },
  {
    id: "43",
    title: "Technical Writing: Documentation on Software Projects",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Technical Writing,Documentation",
    price: 59,
    updatedAt: "2025-07-01T21:00:00Z",
  },
  {
    id: "44",
    title: "Linux Command Line Basics",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Linux,CLI,Bash,SysAdmin",
    price: 69,
    updatedAt: "2025-07-02T22:00:00Z",
  },
  {
    id: "45",
    title: "Tailwind CSS From Scratch | Learn By Building Projects",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Tailwind CSS,CSS,Frontend",
    price: 79,
    updatedAt: "2025-08-01T10:00:00Z",
  },
  {
    id: "46",
    title: "Electron for Desktop Apps: The Complete Developer's Guide",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Electron,Desktop,JavaScript",
    price: 89,
    updatedAt: "2025-08-02T11:00:00Z",
  },
  {
    id: "47",
    title: "The Complete Blender Creator: Learn 3D Modelling",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Blender,3D Modeling,Animation",
    price: 139,
    updatedAt: "2025-08-03T12:00:00Z",
  },
  {
    id: "48",
    title: "Flutter & Dart - The Complete Guide [2025 Edition]",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Flutter,Dart,Mobile,Cross-platform",
    price: 129,
    updatedAt: "2025-08-04T13:00:00Z",
  },
  {
    id: "49",
    title: "API and Web Service Introduction",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "API,REST,Web Services",
    price: 59,
    updatedAt: "2025-08-05T14:00:00Z",
  },
  {
    id: "50",
    title: "Build Web Apps with Strapi (Headless CMS)",
    coverImage: "https://1.bp.blogspot.com/-ttR6sFIgYJw/YHWVnJF1t2I/AAAAAAAAABo/WJWwOLtIH34XRBtuWTWOjX-19_QER92cACPcBGAYYCw/s16000/Learn+Web+Develpoment+TBN.png",
    category: "Strapi,Headless CMS,Backend,API",
    price: 79,
    updatedAt: "2025-08-06T15:00:00Z",
  },
];